name: Modify Pulls
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  modify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'
      
      - name: Run script
        run: node replacer.js
        
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update asset deliverly"
          git push
      
